#!/usr/bin/env bash
# Install a load balancer
# Install haproxy
# Enable dedicated PPA

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web-01 and web-02 servers.
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 224427-web-01 54.87.169.181:80 check
   server 224427-web-02 54.175.136.188:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
