#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80
# Replace the default configuration with a custom one and then restart Nginx to apply changes.
rm -rf /etc/nginx/sites-enabled/*
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
