#!/bin/bash

# Check for the presence of a valid public key argument
if [ $# -eq 0 ]; then
  echo "Usage: $0 <public_key>"
  exit 1
fi

# Define the server SSH connection details
server_user="ubuntu"
server_ip="54.87.169.181"

# SSH into the server and append the provided public key to the authorized_keys file
ssh_command="echo '$1' >> ~/.ssh/authorized_keys"
ssh "$server_user@$server_ip" "$ssh_command"

echo "Public key added to the server's authorized_keys file."
